List<String> phrases = [
  "You have the strength within you to overcome any challenge you face.",
  "Success is not final; it's the courage to keep going that matters.",
  "Stay focused, work hard, and never lose sight of your goals.",
  "Believe in your abilities; you are capable of achieving greatness.",
  "Every small step forward brings you closer to your dreams.",
  "Your mind is a powerful tool; use it to create the life you want.",
  "Challenges are just stepping stones on your path to success.",
  "Trust the process; every effort you make counts towards success.",
  "Hard work and determination will always lead you to victory.",
  "You are not defined by your setbacks but by your comebacks.",
  "Believe you can and you're halfway there.",
  "Success is not final; it's the courage to keep going.",
  "Keep going; each step is progress.",
  "Dream big, work hard, stay focused.",
  "Believe in yourself and all that you are.",
  "Your only limit is your mind.",
  "Turn your dreams into plans and take action.",
  "Stay positive, work hard, make it happen.",
  "Every day is a second chance.",
  "Don't stop until you're proud.",
  "Challenges are what make life interesting.",
  "Stay focused and never give up.",
  "Success is the sum of small efforts repeated.",
  "Dream it, wish it, do it.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Don't wait for opportunity; create it.",
  "Believe in your dreams and they may come true.",
  "Dream big, act bigger.",
  "Make today so awesome yesterday gets jealous.",
  "Life is tough, but so are you.",
  "Stay humble, hustle hard.",
  "Believe in yourself and you will be unstoppable.",
  "Every accomplishment starts with the decision to try.",
  "Push yourself because no one else is going to do it for you.",
  "The only way to do great work is to love what you do.",
  "Success is not for the lazy.",
  "Don’t limit your challenges; challenge your limits.",
  "Your vibe attracts your tribe.",
  "The secret of getting ahead is getting started.",
  "Success doesn’t just find you; you have to go out and get it.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Work hard in silence; let success make the noise.",
  "Don’t stop when you’re tired; stop when you’re done.",
  "The harder you work, the luckier you get.",
  "Life is short; make it count.",
  "Believe in your infinite potential.",
  "Stay strong, make them wonder how you’re still smiling.",
  "Success is the best revenge.",
  "Don’t wait for the right opportunity; create it.",
  "Focus on the journey, not the destination.",
  "Success is not in what you have, but who you are.",
  "Act as if what you do makes a difference. It does.",
  "Do something today that your future self will thank you for.",
  "Your limitation—it’s only your imagination.",
  "Success is a journey, not a destination.",
  "Great things never come from comfort zones.",
  "The best way to predict the future is to create it.",
  "Don’t be pushed around by the fears in your mind.",
  "Success is not for the chosen few; it's for the few who choose.",
  "Make each day your masterpiece.",
  "Dream bigger. Do bigger.",
  "The biggest risk is not taking any risk.",
  "The best revenge is massive success.",
  "You are never too old to set another goal or to dream a new dream.",
  "Don’t count the days; make the days count.",
  "Success is how high you bounce when you hit bottom.",
  "Believe in your dreams, no matter how impossible they seem.",
  "Your passion is waiting for your courage to catch up.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don't happen; you create them.",
  "Don't watch the clock; do what it does. Keep going.",
  "Believe you can and you’re halfway there.",
  "Act as if what you do makes a difference. It does.",
  "Dream big and dare to fail.",
  "Don’t be afraid to give up the good to go for the great.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Success is how high you bounce when you hit bottom.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Success is not a destination; it's a journey.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Success is not for the lazy.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Be not afraid of life. Believe that life is worth living.",
  "Be yourself; everyone else is already taken.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Success is liking yourself, liking what you do, and liking how you do it."
      "Believe in the magic of new beginnings and endless possibilities.",
  "Your vibe attracts your tribe; stay positive and shine bright.",
  "Every day may not be good, but there's something good in every day.",
  "Happiness is a choice; choose it every single day.",
  "Positive thoughts create positive outcomes; think big!",
  "Surround yourself with positivity and watch your life transform.",
  "Your smile is your logo; your personality is your business.",
  "Choose joy; it’s the best kind of rebellion.",
  "Believe you can, and you’re halfway there.",
  "Today is a new day filled with new opportunities.",
  "The sun always shines after the storm; keep your head up.",
  "Fill your life with experiences, not things; focus on happiness.",
  "Embrace the glorious mess that you are.",
  "Let your light shine; it’s the best gift you can give.",
  "Count your blessings, not your problems.",
  "Radiate positivity; it’s contagious!",
  "The best is yet to come; keep moving forward.",
  "Positive thinking leads to positive outcomes.",
  "Every day is a fresh start; make it count.",
  "Be a rainbow in someone else's cloud.",
  "Happiness blooms from within; nurture it daily.",
  "Stay positive; work hard, make it happen.",
  "The world is full of beauty; open your eyes to see it.",
  "Find joy in the little things; they matter most.",
  "Believe in yourself; you are capable of amazing things.",
  "Let go of what doesn’t serve you and embrace positivity.",
  "Every sunrise is an invitation to rise again.",
  "Your attitude determines your direction; choose wisely.",
  "Find something positive in each day, even if it’s small.",
  "The more you praise and celebrate your life, the more there is in life to celebrate.",
  "Good things come to those who hustle and stay positive.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Today’s struggles are tomorrow’s strengths; stay strong.",
  "Gratitude turns what we have into enough.",
  "Happiness is not by chance, but by choice.",
  "Positivity is a superpower; use it wisely.",
  "Life is too short to waste on negativity.",
  "Let your dreams be bigger than your fears.",
  "Believe in your dreams, and they may come true.",
  "The best way to predict your future is to create it.",
  "Every moment is a fresh beginning; make it count.",
  "Positivity is a choice; choose it every day.",
  "Your thoughts shape your reality; think positively.",
  "Chase your dreams, not your fears.",
  "Stay positive; your mindset is your greatest tool.",
  "The only limit to our realization of tomorrow is our doubts.",
  "Let your positivity be a source of inspiration to others.",
  "Embrace the challenges; they will make you stronger.",
  "Happiness is not something ready-made; it comes from your own actions.",
  "Create your own sunshine and let it shine bright.",
  "Every day is a new beginning; take a deep breath and start again.",
  "Positive energy is infectious; spread it wherever you go.",
  "The key to happiness is letting each situation be what it is.",
  "Focus on the good, and the good gets better.",
  "Life is like a camera; focus on what’s important.",
  "Choose to be happy; it’s a decision worth making.",
  "Let go of negativity; it serves no purpose.",
  "The journey of a thousand miles begins with a single step.",
  "Your happiness is a reflection of your mindset; cultivate it.",
  "The more you focus on gratitude, the more reasons you find to be grateful.",
  "Choose happiness over perfection.",
  "Live in the moment; it’s all we really have.",
  "Embrace the beauty of the present; it’s a gift.",
  "Stay positive, work hard, and make it happen.",
  "Every day may not be perfect, but there’s something perfect in every day.",
  "The sky is not the limit; your mind is.",
  "Create your own path and follow it with positivity.",
  "Stay hopeful; better days are coming.",
  "Believe in yourself and all that you are.",
  "Every challenge is an opportunity to grow and learn.",
  "The only way to do great work is to love what you do.",
  "Your attitude is your window to the world; keep it positive.",
  "Life is better when you’re laughing.",
  "Find joy in the journey, not just the destination.",
  "The more you share positivity, the more it grows.",
  "Live your life to the fullest and focus on the positive.",
  "Embrace every moment; they’re fleeting but precious.",
  "Your smile can change the world; use it generously.",
  "Stay positive, even when it’s tough; it’ll get better.",
  "The best things in life are the people we love and the memories we make.",
  "Be the reason someone smiles today.",
  "Life is a collection of moments; make them count.",
  "Choose to see the good in every situation.",
  "Find your happiness within, and it will radiate outward.",
  "Stay patient and trust your journey; it’s unfolding beautifully.",
  "Positive minds lead to positive lives.",
  "Let positivity guide your thoughts and actions.",
  "Your life is your story; make it a positive one.",
  "Embrace challenges with an open heart and mind.",
  "The world needs more kindness; be a part of it.",
  "Focus on the good, and let the bad fade away.",
  "Stay curious and keep learning; it fuels positivity.",
  "Create a life you love and fill it with joy.",
  "The more you believe in yourself, the more positive energy you radiate.",
  "Find beauty in the ordinary; it’s all around you.",
  "Live life with no excuses and travel with no regret.",
  "Let positivity be your guide in all that you do.",
  "Be the light that brightens someone’s day.",
  "Life is a gift; unwrap it with joy and gratitude.",
  "Every day is a new chance to find your happiness.",
  "Positive thoughts are the seeds of a happy life.",
  "Surround yourself with those who lift you higher.",
  "Believe in the power of your dreams and pursue them.",
  "Happiness is a choice; make it your daily decision.",
  "Every sunrise is a new opportunity to shine.",
  "Fill your heart with joy, and let it overflow.",
  "Focus on the good, and the good gets even better.",
  "Let go of negativity; it doesn’t serve you.",
  "Smile more; it’s the best accessory you can wear.",
  "Embrace every moment; they’re all part of the journey.",
  "Positivity breeds positivity; share it generously.",
  "The secret to happiness is finding joy in the little things.",
  "Chase your dreams with enthusiasm and passion.",
  "Choose to see the beauty in every day.",
  "Be the energy you want to attract.",
  "Your happiness is your responsibility; own it.",
  "Let your heart be light and your thoughts be positive.",
  "Create a life that makes you want to jump out of bed each morning.",
  "Focus on progress, not perfection; every step counts.",
  "Stay optimistic; the best is yet to come.",
  "Your smile has the power to light up the room.",
  "Every day is a chance to create new memories.",
  "Believe in yourself and all that you can achieve.",
  "Surround yourself with positivity, and watch your life transform.",
  "Find joy in the journey, not just the destination.",
  "Choose gratitude over complaining; it changes everything.",
  "Life is a beautiful ride; enjoy every twist and turn.",
  "Stay hopeful; tomorrow is a fresh start.",
  "Live for today, for tomorrow is never promised.",
  "Positivity is a mindset; cultivate it daily.",
  "Every challenge is a stepping stone to greatness.",
  "Radiate love and positivity, and watch it return to you.",
  "Let your dreams be your compass; follow them bravely.",
  "The only limit to your happiness is your mindset.",
  "Every moment is an opportunity to be positive.",
  "Create your own sunshine, even on cloudy days.",
  "Focus on what you can control and let go of the rest.",
  "Every day may not be good, but there’s something good in every day.",
  "Your attitude determines your direction; choose positivity.",
  "Find beauty in the chaos; it’s where magic happens.",
  "Believe in your potential; you’re capable of greatness.",
  "Life is too short for negativity; embrace the positive.",
  "Positivity is contagious; spread it around.",
  "Stay curious, stay positive, and keep exploring.",
  "Your journey is uniquely yours; embrace it with joy.",
  "Count your blessings; they’re more than you realize.",
  "Embrace the challenges; they shape you into who you are.",
  "Stay grounded, keep your heart open, and let positivity flow.",
  "Life is a canvas; paint it with vibrant colors of joy.",
  "Let go of what weighs you down and soar high.",
  "Stay positive and focused; success is on the horizon.",
  "Believe in the power of kindness; it can change the world.",
  "Life is a collection of moments; make them joyful.",
  "Embrace every opportunity; they lead to growth.",
  "Positive thinking is the first step to positive actions.",
  "Every sunset brings the promise of a new dawn.",
  "Let your heart be your guide; it knows the way.",
  "Surround yourself with positivity and let it lift you.",
  "Life is about balance; find your happy medium.",
  "Every day is a new page in your story; make it beautiful.",
  "Let positivity flow from you like a river.",
  "Choose to be the best version of yourself every day.",
  "Find peace in the chaos; it’s where you grow.",
  "Embrace your uniqueness; it’s your superpower.",
  "Focus on the good; it’s always there if you look.",
  "Positivity is the key to unlocking your potential.",
  "Every setback is a setup for a comeback.",
  "Stay true to yourself and let your light shine.",
  "Believe in the magic of possibilities; they’re endless.",
  "Let your passion guide you toward happiness.",
  "Every small step you take leads to great distances.",
  "Create a life that inspires you every single day.",
  "Positivity is the bridge to a happier life.",
  "Your dreams are valid; pursue them relentlessly.",
  "Stay optimistic, even when times are tough.",
  "Life is a journey; enjoy every step along the way.",
  "Let joy be your compass; it’ll guide you well.",
  "Every day is a new beginning; embrace it wholeheartedly.",
  "Believe in your ability to create a positive change.",
  "Focus on what lifts you up; let go of what pulls you down.",
  "Your vibe attracts your tribe; be a positive force.",
  "Every moment holds the potential for happiness.",
  "Find strength in the struggles; they make you resilient.",
  "Surround yourself with positive people; they inspire growth.",
  "Life is a gift; unwrap it with gratitude and joy.",
  "Choose happiness, even in the face of adversity.",
  "Positivity is the sun that brightens the darkest days.",
  "Stay focused on your goals; they’re within reach.",
  "Believe in yourself; you’re stronger than you think.",
  "Find joy in the process, not just the outcome.",
  "Every breath is a chance to start anew; embrace it.",
  "Your happiness is a reflection of your mindset.",
  "Stay curious and open-minded; it fuels positivity.",
  "Life is an adventure; embrace every moment of it.",
  "Let your light shine brightly; the world needs it.",
  "Choose joy over fear; it’s a powerful choice.",
  "Every sunrise brings new hope; seize it with joy.",
  "Focus on the present; it’s where happiness resides.",
  "Believe in your dreams, and let them lead you.",
  "Let your heart be filled with gratitude and positivity.",
  "Embrace change; it often leads to beautiful transformations.",
  "Stay hopeful and keep pushing forward; you’re almost there."
      "Positivity is the fuel that keeps your spirit alive.",
  "Find joy in the little things; they make life beautiful.",
  "Every day holds new possibilities; embrace them.",
  "Your smile can brighten someone’s darkest day.",
  "Let happiness be your guide; it knows the way.",
  "Embrace every moment; they’re all part of your journey.",
  "Positive vibes only; leave negativity behind.",
  "Believe in the goodness of people; it’s everywhere.",
  "Choose love over fear; it’s a powerful choice.",
  "Let gratitude fill your heart; it brings joy.",
  "Every step you take is a step toward your dreams.",
  "Your happiness is in your hands; create it.",
  "Find peace in the chaos; it’s where you grow.",
  "Surround yourself with positivity; it lifts you higher.",
  "Every sunrise is a fresh start; make it count.",
  "Let your heart be light and your thoughts be positive.",
  "Celebrate your small victories; they lead to big wins.",
  "Stay curious and open-minded; it fuels happiness.",
  "Every moment is an opportunity to choose joy.",
  "Positivity transforms challenges into opportunities.",
  "Believe in the magic of new beginnings.",
  "Your thoughts shape your reality; think positively.",
  "Embrace the journey; it’s where the magic happens.",
  "Fill your life with laughter; it’s the best medicine.",
  "Every day is a new chance to shine.",
  "Stay focused on your goals; you’re getting closer.",
  "Let your light shine brightly for all to see.",
  "Choose joy, even when times are tough.",
  "Positivity is the antidote to burnout; embrace it.",
  "Believe in your power to create change.",
  "Every challenge is a stepping stone to growth.",
  "Stay positive and watch how life unfolds beautifully.",
  "Your attitude determines your direction; choose wisely.",
  "Find beauty in every moment; it’s all around you.",
  "Let go of negativity; it only weighs you down.",
  "Every breath is a chance to start anew.",
  "Positivity is a mindset; cultivate it daily.",
  "Believe in yourself and all that you can achieve.",
  "Every small step counts; keep moving forward.",
  "Embrace each day with gratitude and enthusiasm.",
  "Life is a beautiful journey; enjoy the ride.",
  "Your happiness is your responsibility; own it.",
  "Choose positivity; it makes everything better.",
  "Every setback is a setup for a comeback.",
  "Stay hopeful; the best is yet to come.",
  "Find joy in the process, not just the outcome.",
  "Your vibe attracts your tribe; be a positive force.",
  "Embrace challenges; they help you grow stronger.",
  "Life is too short for negativity; spread positivity.",
  "Let your dreams be your guide; follow them fiercely.",
  "Focus on what lifts you up; let go of what pulls you down.",
  "Surround yourself with those who inspire you.",
  "Let your heart be your compass; it knows the way.",
  "Every day is a new page in your story; make it beautiful.",
  "Believe in the power of kindness; it can change the world.",
  "Stay true to yourself; you’re enough just as you are.",
  "Life is a gift; unwrap it with joy and gratitude.",
  "Embrace the unknown; it often leads to great adventures.",
  "Choose happiness, even in the face of adversity.",
  "Your thoughts are powerful; choose them wisely.",
  "Every moment holds the potential for happiness.",
  "Stay curious; it keeps your spirit alive.",
  "Let positivity flow from you like a river.",
  "Find strength in the struggles; they make you resilient.",
  "Every sunrise brings new hope; seize it with joy.",
  "Focus on what you can control; let go of the rest.",
  "Believe in your dreams; they’re worth pursuing.",
  "Embrace every opportunity; they lead to growth.",
  "Let your heart be filled with love and gratitude.",
  "Stay optimistic; your best days are ahead.",
  "Life is an adventure; embrace every twist and turn.",
  "Your happiness is a reflection of your mindset.",
  "Choose joy over fear; it’s a powerful choice.",
  "Every breath is a chance to start anew; embrace it.",
  "Let go of what weighs you down and soar high.",
  "Stay focused on the positive; it changes everything.",
  "Believe in the beauty of your dreams.",
  "Find joy in the journey; it’s where you grow.",
  "Let your light shine brightly; the world needs it.",
  "Choose to see the good in every situation.",
  "Embrace the chaos; it often leads to beauty.",
  "Your happiness is contagious; spread it generously.",
  "Every moment is an opportunity to be positive.",
  "Stay grounded, keep your heart open, and let positivity flow.",
  "Life is a canvas; paint it with vibrant colors of joy.",
  "Surround yourself with positive energy; it lifts you up.",
  "Focus on progress, not perfection; every step counts.",
  "Stay hopeful and keep pushing forward; you’re almost there.",
  "Believe in the power of your positivity.",
  "Let your dreams inspire you to take action.",
  "Find peace in the chaos; it’s where you thrive.",
  "Embrace change; it often leads to beautiful transformations."
      "Find happiness in every moment; it’s a choice.",
  "Your smile is a reflection of your inner joy.",
  "Embrace positivity; it transforms your outlook on life.",
  "Let every day be a new opportunity for joy.",
  "Focus on the good, and the good gets better.",
  "Choose kindness; it’s a powerful force for good.",
  "Positivity is contagious; spread it wherever you go.",
  "Every moment is a chance to create happiness.",
  "Believe in yourself; you’re capable of amazing things.",
  "Let gratitude be your guiding light.",
  "Find beauty in the simple things; they bring joy.",
  "Your positivity can change the world around you.",
  "Embrace challenges as opportunities to grow.",
  "Stay hopeful; brighter days are ahead.",
  "Your thoughts shape your reality; think positively.",
  "Every step you take brings you closer to joy.",
  "Let laughter fill your days; it’s the best medicine.",
  "Find joy in the journey, not just the destination.",
  "Surround yourself with positivity; it lifts your spirit.",
  "Every sunrise brings new possibilities; embrace them.",
  "Let your heart be light and your mind be clear.",
  "Positivity fuels resilience; keep it close.",
  "Choose happiness, no matter the circumstances.",
  "Let go of negativity; it only holds you back.",
  "Your happiness is a choice; make it daily.",
  "Stay curious and open to new experiences.",
  "Find strength in every struggle; it makes you stronger.",
  "Believe in the magic of everyday moments.",
  "Your smile can brighten someone’s day; share it.",
  "Embrace life with open arms and a grateful heart.",
  "Every challenge is a stepping stone to greatness.",
  "Choose joy; it’s a powerful mindset.",
  "Find peace in the present moment; it’s a gift.",
  "Your journey is unique; embrace it fully.",
  "Let positivity guide your path; it leads to joy.",
  "Every setback is a setup for a comeback.",
  "Stay positive; it changes everything.",
  "Find the silver lining in every cloud.",
  "Let your dreams inspire you to take action.",
  "Every small step forward counts; keep going.",
  "Embrace positivity; it’s a powerful force.",
  "Your happiness is in your hands; create it.",
  "Choose to see the good in every situation.",
  "Find joy in the little things; they matter most.",
  "Every day is a chance to start fresh; seize it.",
  "Let your heart be filled with love and joy.",
  "Stay focused on what brings you happiness.",
  "Life is an adventure; enjoy every moment.",
  "Believe in your ability to create positive change.",
  "Your vibe attracts your tribe; be positive.",
  "Choose to uplift others; it brightens your spirit.",
  "Every moment is an opportunity for happiness.",
  "Stay optimistic; it attracts positive outcomes.",
  "Find joy in the process; it’s where the growth happens.",
  "Embrace the unknown; it often leads to beauty.",
  "Your happiness is contagious; spread it generously.",
  "Let go of what doesn’t serve you; embrace positivity.",
  "Stay true to yourself; it brings inner peace.",
  "Life is a gift; unwrap it with joy and gratitude.",
  "Believe in the beauty of your dreams.",
  "Every challenge is an opportunity to shine.",
  "Let positivity be your compass in life.",
  "Find strength in the journey; it’s where you grow.",
  "Choose love, joy, and positivity every day.",
  "Your thoughts are powerful; make them uplifting.",
  "Every breath is a chance to start anew.",
  "Stay focused on the good; it multiplies.",
  "Find happiness in the journey, not just the goal.",
  "Let your light shine bright; the world needs it.",
  "Embrace every moment with gratitude and joy.",
  "Your attitude determines your altitude; choose wisely.",
  "Every step forward is progress; keep moving.",
  "Believe in the power of positivity; it’s transformative.",
  "Find joy in the simple pleasures of life.",
  "Stay positive; it fuels your spirit.",
  "Choose happiness; it’s a daily commitment.",
  "Every setback is a setup for growth.",
  "Let your heart be your guide; it knows the way.",
  "Surround yourself with uplifting energy; it empowers you.",
  "Life is a beautiful journey; enjoy the ride.",
  "Find beauty in every day; it’s all around you.",
  "Embrace positivity; it changes your perspective.",
  "Your happiness is a reflection of your mindset.",
  "Every day is a new chance to spread joy.",
  "Stay hopeful; the best is yet to come.",
  "Let positivity flow through you; it inspires others.",
  "Choose joy, even when times are tough.",
  "Your journey is your own; embrace it with love.",
  "Find strength in every challenge; it builds resilience.",
  "Every moment is a gift; cherish it with gratitude.",
  "Believe in the power of your dreams; they matter.",
  "Stay positive, and watch how life unfolds beautifully."
];
